-- Neutral News — Supabase schema
-- Run this in the Supabase SQL editor (or the SpinDetector project if sharing one database)

-- Articles generated by the neutral news pipeline
create table if not exists neutral_articles (
  id                    bigint generated always as identity primary key,
  date                  date not null,
  cluster_id            text not null,
  topic_label           text not null,
  headline              text not null,
  summary               text,
  body                  text not null,
  key_facts             text[] default '{}',
  "references"          text[] default '{}',
  outlet_count          int default 0,
  sources_used          text[] default '{}',

  -- Grok review metadata
  grok_review_score     numeric(4,2),
  grok_review_issues    jsonb default '[]',
  grok_reviewer         text,    -- 'grok', 'claude-fallback'

  -- Claude final validation
  validation_approved   boolean default false,
  validation_confidence numeric(4,2),
  validation_neutrality text,    -- 'Excellent', 'Good', 'Acceptable', 'Needs Revision'
  validation_notes      text,
  validation_reviewed_at timestamptz,

  published_at          timestamptz default now(),

  unique(date, cluster_id)
);

-- Pipeline run log
create table if not exists neutral_pipeline_runs (
  id                   bigint generated always as identity primary key,
  date                 date not null,
  articles_generated   int default 0,
  elapsed_seconds      int,
  status               text not null,   -- 'success', 'error'
  error_message        text,
  created_at           timestamptz default now()
);

-- Enable row-level security (public read-only)
alter table neutral_articles enable row level security;
alter table neutral_pipeline_runs enable row level security;

create policy "Public read neutral_articles"
  on neutral_articles for select using (true);

create policy "Service role write neutral_articles"
  on neutral_articles for all
  to service_role using (true) with check (true);

create policy "Public read neutral_pipeline_runs"
  on neutral_pipeline_runs for select using (true);

create policy "Service role write neutral_pipeline_runs"
  on neutral_pipeline_runs for all
  to service_role using (true) with check (true);

-- Index for fast homepage query
create index if not exists idx_neutral_articles_date
  on neutral_articles (date desc, outlet_count desc);
