import Link from 'next/link'
import { NeutralArticle } from '@/lib/types'
import ValidationBadge from './ValidationBadge'
import AdSlot from './AdSlot'

interface Props {
  article: NeutralArticle
}

export default function ArticleDetail({ article }: Props) {
  const publishedDate = new Date(article.published_at).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const publishedTime = new Date(article.published_at).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    timeZoneName: 'short',
  })

  const paragraphs = article.body.split('\n\n').filter(Boolean)

  return (
    <div className="max-w-2xl mx-auto">
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-800 transition-colors mb-8"
      >
        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
          <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
        </svg>
        Today&apos;s news
      </Link>

      <div className="mb-2">
        <span className="text-[11px] uppercase tracking-widest text-slate-400 font-medium">
          {article.topic_label}
        </span>
      </div>

      <h1 className="font-serif text-3xl sm:text-4xl text-slate-900 leading-tight mb-5">
        {article.headline}
      </h1>

      <p className="text-lg text-slate-600 leading-relaxed border-l-2 border-slate-900 pl-4 mb-6">
        {article.summary}
      </p>

      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-400 mb-8 pb-6 border-b border-slate-200">
        <span>{publishedDate} · {publishedTime}</span>
        <span>{article.outlet_count} outlets reporting</span>
        <span className="uppercase">Sources: {article.sources_used.join(', ')}</span>
      </div>

      <div className="mb-10">
        {paragraphs.map((para, i) => (
          <p key={i} className="font-serif text-slate-800 leading-[1.8] mb-5 text-[17px]">
            {para}
          </p>
        ))}
      </div>

      {article.key_facts.length > 0 && (
        <div className="border border-slate-200 rounded p-5 bg-slate-50 mb-6">
          <h3 className="text-[11px] uppercase tracking-widest text-slate-500 font-semibold mb-3">
            Key Facts
          </h3>
          <ul className="space-y-2">
            {article.key_facts.map((fact, i) => (
              <li key={i} className="flex gap-2.5 text-sm text-slate-700">
                <span className="text-slate-300 flex-shrink-0">—</span>
                {fact}
              </li>
            ))}
          </ul>
        </div>
      )}

      {article.references?.length > 0 && (
        <div className="mb-6">
          <h3 className="text-[11px] uppercase tracking-widest text-slate-500 font-semibold mb-3">
            References
          </h3>
          <ol className="space-y-1.5">
            {article.references.map((ref, i) => (
              <li key={i} className="flex gap-2.5 text-xs text-slate-500 leading-relaxed">
                <span className="flex-shrink-0 tabular-nums text-slate-400">{i + 1}.</span>
                <span>{ref}</span>
              </li>
            ))}
          </ol>
        </div>
      )}

      <ValidationBadge article={article} />

      <AdSlot slot="article-footer" format="rectangle" />

      <div className="mt-8 pt-6 border-t border-slate-200">
        <p className="text-xs text-slate-400 leading-relaxed">
          This article was generated by an AI pipeline that identifies the most-reported stories of
          the day from SpinDetector.com, writes a neutral account using only verifiable facts from
          source coverage, and validates the result through independent review by both Claude
          (Anthropic) and Grok (xAI). No editorial judgment has been applied.{' '}
          <Link href="/about" className="underline decoration-slate-300 underline-offset-2 hover:text-slate-600">
            Read our methodology
          </Link>
          . Corrections:{' '}
          <a href="mailto:piers@spindetector.com" className="underline decoration-slate-300 underline-offset-2 hover:text-slate-600">
            piers@spindetector.com
          </a>
        </p>
      </div>
    </div>
  )
}
