import type { Metadata } from 'next'

/**
 * The one canonical origin for the site.
 *
 * The apex `neutralnews.us` 308-redirects to `www`, so every URL we emit —
 * canonical tags, sitemap entries, RSS links — must be the www form. Pointing
 * them at the apex would make every canonical a redirect, which is a weak and
 * ambiguous signal to crawlers.
 */
export const SITE_URL = 'https://www.neutralnews.us'

export const SITE_NAME = 'Neutral News'

export const SITE_DESCRIPTION =
  "Five of today's top stories, written to the highest standards of factual accuracy and political neutrality. Independently reviewed by Claude and Grok."

/** Where corrections, press and feedback go. Also the RSS managing editor. */
export const CONTACT_EMAIL = 'piers@spindetector.com'

export const RSS_PATH = '/rss.xml'

/** Default social card, 1200×630. Generated by app/og.png/route.tsx. */
export const OG_IMAGE_PATH = '/og.png'

/** Publisher logo for structured data, 600×60. Generated by app/logo.png. */
export const LOGO_PATH = '/logo.png'

/** Absolute URL for a site-relative path, e.g. canonical('/about'). */
export function canonical(path = '/'): string {
  return new URL(path, SITE_URL).toString()
}

/**
 * Canonical tag plus the RSS autodiscovery link, for one page.
 *
 * Metadata objects are merged shallowly by key, so a page that declares its own
 * `alternates` replaces the layout's wholesale. Every page therefore has to
 * carry the feed link itself, or setting a canonical silently drops it.
 */
export function alternatesFor(path = '/'): Metadata['alternates'] {
  return {
    canonical: canonical(path),
    types: {
      'application/rss+xml': [
        { url: canonical(RSS_PATH), title: `${SITE_NAME} — Today's top stories` },
      ],
    },
  }
}
